import Head from "next/head";
import BaseStyles from "@styles/globalStyles";
import Header from "@components/Header";
import styled from "styled-components";

function Layout({ children }) {
  return (
    <>
      <BaseStyles />
      <div>
        <Head>
          <title>Bejamas Test</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            rel="preload"
            href="/fonts/archivo/Archivo-Bold.woff"
            as="font"
            crossOrigin=""
          />
          <link
            rel="preload"
            href="/fonts/archivo/Archivo-Regular.woff"
            as="font"
            crossOrigin=""
          />
          <link
            rel="preload"
            href="/fonts/archivo/Archivo-Bold.woff2"
            as="font"
            crossOrigin=""
          />
          <link
            rel="preload"
            href="/fonts/archivo/Archivo-Regular.woff2"
            as="font"
            crossOrigin=""
          />
        </Head>

        <LayoutWrapper>
          <Header />
          <div>{children}</div>
        </LayoutWrapper>
      </div>
    </>
  );
}
const LayoutWrapper = styled.div`
  padding: 0 40px;

  @media screen and (max-width: 768px) {
    padding: 0 10px;
  }
`;

export default Layout;
