import Head from "next/head"
import BaseStyles from '@styles/globalStyles';


function Layout({children}) {
    return (
        <>
        <BaseStyles/>
        <div>
            <Head>
                <title>Bejamas Test</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                {children}
            </div>
        </div>
        </>
    )
}

export default Layout
